{% set name = "connexion" %}
{% set version = "2.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/connexion-{{ version }}.tar.gz
  sha256: 1ccfac57d4bb7adf4295ba6f5e48f5a1f66057df6a0713417766c9b5235182ee

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - connexion = connexion.cli:main

requirements:
  build:
    - python >=3.6
    - pip
    - flake8

  run:
    - python >=3.6
    - clickclick >=1.2
    - jsonschema >=2.5.1
    - pyyaml >=5.1
    - requests >=2.9.1
    - inflection >=0.3.1
    - flask >=1.0.4
    - openapi-spec-validator >=0.2.4

test:
  imports:
    - connexion
    - connexion.apis
    - connexion.apps
    - connexion.decorators
  commands:
    - connexion --version
    - pip check
  requires:
    - pip

about:
  home: https://github.com/zalando/connexion
  license: Apache-2.0
  summary: Swagger/OpenAPI First framework for Python on top of Flask with automatic endpoint validation & OAuth2 support
  license_family: APACHE
  license_file: LICENSE.txt
  dev_url: https://github.com/zalando/connexion
  doc_url: https://connexion.readthedocs.io/

extra:
  recipe-maintainers:
    - rvalieris
    - xylar
