{% set name = "connexion" %}
{% set version = "3.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/connexion-{{ version }}.tar.gz
  sha256: 66a44580991f53955b6e409a84fa9fa65c7ca4db52dc217b49cd35c201066083

build:
  entry_points:
    - connexion = connexion.cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8,<4.0
    - poetry-core >=1.2.0
    - pip

  run:
    - python >=3.8.0,<4.0.0
    - asgiref >=3.4
    - httpx >=0.23
    - inflection >=0.3.1
    - jsonschema >=4.17.3
    - jinja2 >=3.0.0
    - python-multipart >=0.0.5
    - pyyaml >=5.1
    - requests >=2.27
    - starlette >=0.35
    - typing-extensions >=4.6.1
    - werkzeug >=2.2.1
  run_constrained:
    - a2wsgi >=1.7
    - flask >=2.2
    - swagger-ui-bundle >=1.1.0
    - uvicorn >=0.17.6

test:
  imports:
    - connexion
    - connexion.apps
    - connexion.decorators
  commands:
    - connexion --version
    - pip check
  requires:
    - pip

about:
  home: https://github.com/spec-first/connexion
  license: Apache-2.0
  summary: Connexion - API first applications with OpenAPI/Swagger
  license_family: APACHE
  license_file: LICENSE
  dev_url: https://github.com/spec-first/connexion
  doc_url: https://connexion.readthedocs.io/

extra:
  recipe-maintainers:
    - rvalieris
    - xylar
