{% set name = "connexion" %}
{% set version = "3.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/connexion-{{ version }}.tar.gz
  sha256: 9d0f09370084b3885fd9d004cf3ccfe6234afbb70e2e4daa17ca7e00f62a74fd

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - connexion = connexion.cli:main

requirements:
  host:
    - python >=3.8
    - pip
    - flake8

  run:
    - python >=3.8
    - clickclick >=1.2,<21
    - jsonschema >=2.5.1,<5
    - pyyaml >=5.1,<7
    - requests >=2.9.1,<3
    - inflection >=0.3.1,<0.6
    - werkzeug >=1.0,<2.3
    - packaging >=20
    - flask >=1.0.4,<2.3
    - itsdangerous >=0.24

test:
  imports:
    - connexion
    - connexion.apis
    - connexion.apps
    - connexion.decorators
  commands:
    - connexion --version
    - pip check
  requires:
    - pip

about:
  home: https://github.com/zalando/connexion
  license: Apache-2.0
  summary: Swagger/OpenAPI First framework for Python on top of Flask with automatic endpoint validation & OAuth2 support
  license_family: APACHE
  license_file: LICENSE.txt
  dev_url: https://github.com/zalando/connexion
  doc_url: https://connexion.readthedocs.io/

extra:
  recipe-maintainers:
    - rvalieris
    - xylar
