{% set name = "connexion" %}
{% set version = "2.12.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/connexion-{{ version }}.tar.gz
  sha256: c08b530418a1c448d34cd142713ddd1b245e7694f45cd80533fe8538b64aa7eb

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - connexion = connexion.cli:main

requirements:
  host:
    - python >=3.6
    - pip
    - flake8

  run:
    - python >=3.6
    - clickclick >=1.2,<21
    - inflection >=0.3.1,<0.6
    - jsonschema >=2.5.1,<5
    # there's a bad build openapi-spec-validator 0.3.2 giving us trouble
    - openapi-spec-validator >0.3.2,<0.4
    - pyyaml >=5.1,<6
    - requests >=2.9.1,<3
    - werkzeug >=1.0,<3.0

    # flask extra
    - flask >=1.0.4,<3

test:
  imports:
    - connexion
    - connexion.apis
    - connexion.apps
    - connexion.decorators
  commands:
    - connexion --version
    - pip check
  requires:
    - pip

about:
  home: https://github.com/zalando/connexion
  license: Apache-2.0
  summary: Swagger/OpenAPI First framework for Python on top of Flask with automatic endpoint validation & OAuth2 support
  license_family: APACHE
  license_file: LICENSE.txt
  dev_url: https://github.com/zalando/connexion
  doc_url: https://connexion.readthedocs.io/

extra:
  recipe-maintainers:
    - rvalieris
    - xylar
