{% set name = "connexion" %}
{% set version = "2.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/connexion-{{ version }}.tar.gz
  sha256: 0105b03ea1c54fa0e8160825c729e416b8bd6bf3f007981b04c92ce6d5ae990b

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - connexion = connexion.cli:main

requirements:
  host:
    - python >=3.6
    - pip
    - flake8

  run:
    - python >=3.6
    - clickclick >=1.2,<21
    - flask >=1.0.4,<2
    - inflection >=0.3.1,<0.6
    - jsonschema >=2.5.1,<4
    - openapi-spec-validator >=0.2.4,<0.4
    - pyyaml >=5.1,<6
    - requests >=2.9.1,<3
    - werkzeug >=1.0,<2.0

test:
  imports:
    - connexion
    - connexion.apis
    - connexion.apps
    - connexion.decorators
  commands:
    - connexion --version
    - pip check
  requires:
    - pip

about:
  home: https://github.com/zalando/connexion
  license: Apache-2.0
  summary: Swagger/OpenAPI First framework for Python on top of Flask with automatic endpoint validation & OAuth2 support
  license_family: APACHE
  license_file: LICENSE.txt
  dev_url: https://github.com/zalando/connexion
  doc_url: https://connexion.readthedocs.io/

extra:
  recipe-maintainers:
    - rvalieris
    - xylar
