{% set name = "connexion" %}
{% set version = "3.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/connexion-{{ version }}.tar.gz
  sha256: 0715d4a0393437aa2a48c144756360f9b5292635a05fd15c38cbbaf04ef5acb9

build:
  number: 1
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - poetry-core >=1.2.0
    - pip
  run:
    - python >={{ python_min }},<4.0.0

outputs:
  - name: {{ name }}
    build:
      noarch: python
      script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

    requirements:
      host:
        - python {{ python_min }}
        - poetry-core >=1.2.0
        - pip

      run:
        - python >={{ python_min }},<4.0.0
        - asgiref >=3.4
        - httpx >=0.23
        - inflection >=0.3.1
        - jsonschema >=4.17.3
        - jinja2 >=3.0.0
        - python-multipart >=0.0.15
        - pyyaml >=5.1
        - requests >=2.27
        - starlette >=0.35
        - typing_extensions >=4.6.1
        - werkzeug >=2.2.1

    test:
      imports:
        - connexion
        - connexion.apps
        - connexion.decorators
      commands:
        - connexion --version
        - pip check
      requires:
        - pip
        - python {{ python_min }}

  - name: {{ name }}-with-flask
    build:
      noarch: python
    requirements:
      host:
        - python {{ python_min }}
      run:
        - python >={{ python_min }}
        - {{ pin_subpackage(name, max_pin='x.x.x.x.x.x') }}
        - a2wsgi >=1.7
        - flask >=2.2
        # replace with flask-with-async as soon as available
        # flask[async] extra
        - asgiref >=3.2
    test:
      requires:
        - pip
        - python {{ python_min }}
      imports:
        - connexion
        - connexion.apps.flask
      commands:
        - pip check

  - name: {{ name }}-with-swagger-ui
    build:
      noarch: python
    requirements:
      host:
        - python {{ python_min }}
      run:
        - python >={{ python_min }}
        - {{ pin_subpackage(name, max_pin='x.x.x.x.x.x') }}
        - swagger-ui-bundle >=1.1.0
    test:
      requires:
        - pip
        - python {{ python_min }}
      imports:
        - connexion
        - swagger_ui_bundle
      commands:
        - pip check

  - name: {{ name }}-with-uvicorn
    build:
      noarch: python
    requirements:
      host:
        - python {{ python_min }}
      run:
        - python >={{ python_min }}
        - {{ pin_subpackage(name, max_pin='x.x.x.x.x.x') }}
        - uvicorn-standard >=0.17.6

    test:
      requires:
        - pip
        - python {{ python_min }}
      imports:
        - connexion
        - uvicorn
      commands:
        - pip check

about:
  home: https://github.com/spec-first/connexion
  summary: Connexion - API first applications with OpenAPI/Swagger
  license: Apache-2.0
  license_family: APACHE
  license_file:
    - LICENSE
    - NOTICE
  dev_url: https://github.com/spec-first/connexion
  doc_url: https://connexion.readthedocs.io/

extra:
  recipe-maintainers:
    - rvalieris
    - xylar
